[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
zksync = "https://testnet.era.zksync.dev"
holesky = "https://ethereum-holesky.publicnode.com"
